apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gradle-build
spec:
  inputs:
    params:
      - name: GRADLE_PROPERTIES
        description: System properties of gradle
        type: string
        default: ""
      - name: GRADLE_TASK
        description: The Gradle task to run
        type: string
        default: "build"
    resources:
    - name: source
      type: git
  steps:
    - name: build
      image: gradle:jdk8
      workingDir: /workspace/source/app
      command:
        - /bin/bash 
        - -c
      args:
        - |-
          gradle $(inputs.params.GRADLE_PROPERTIES) $(inputs.params.GRADLE_TASK)
      securityContext:
        privileged: true 

